# HYPOTHESIS TESTING

**Hypothesis testing is used to determine whether observed patterns in the dataset are statistically significant or occurred by chance.
In this analysis, statistical tests are performed to evaluate relationships between customer behavior and spending patterns.**

In [20]:
import pandas as pd
from scipy import stats

In [21]:
df = pd.read_csv(r"C:\Users\sainudheen\OneDrive - KEO International Consultants\Desktop\EDA_Project\Data\cleaned_data_day2.csv")

df.head()

,customer_id,order_id,order_date,order_time,day_of_week,order_channel,store_id,store_location_type,region,customer_age_group,customer_gender,is_rewards_member,cart_size,num_customizations,total_spend,fulfillment_time_min,drink_category,has_food_item,order_ahead,customer_satisfaction
0,CUST_12974,ORD_00000001,2024-03-25,08:47:00,Mon,drive-thru,STR_340,Suburban,southwest,18-24,male,False,5,0,14.48,8.2,refresher,False,False,4
1,CUST_08235,ORD_00000002,2025-07-18,08:02:00,Fri,mobile app,STR_425,Urban,northeast,35-44,female,True,1,3,9.52,5.4,brewed coffee,False,True,4
2,CUST_00393,ORD_00000003,2025-01-15,05:40:00,Wed,kiosk,STR_103,Suburban,midwest,25-34,female,False,2,1,9.32,4.9,brewed coffee,False,False,5
3,CUST_06936,ORD_00000004,2024-07-30,15:10:00,Tue,drive-thru,STR_318,Suburban,midwest,25-34,female,True,2,1,9.55,3.5,refresher,False,False,4
4,CUST_09800,ORD_00000005,2024-06-18,07:38:00,Tue,drive-thru,STR_338,Suburban,northeast,35-44,female,False,3,1,12.24,4.1,frappuccino,False,False,3

In [22]:
df.columns

Index(['customer_id', 'order_id', 'order_date', 'order_time', 'day_of_week',
       'order_channel', 'store_id', 'store_location_type', 'region',
       'customer_age_group', 'customer_gender', 'is_rewards_member',
       'cart_size', 'num_customizations', 'total_spend',
       'fulfillment_time_min', 'drink_category', 'has_food_item',
       'order_ahead', 'customer_satisfaction'],
      dtype='object')

## Independent T-Test

**The independent t-test was conducted to determine whether there is a statistically significant difference in the average spending between rewards members and non-members.**

**H₀: There is no significant difference in the mean total spending between rewards members and non-members.**

**H₁: There is a significant difference in the mean total spending between rewards members and non-members.**

In [23]:
members = df[df["is_rewards_member"] == True]["total_spend"]
non_members = df[df["is_rewards_member"] == False]["total_spend"]

t_stat, p_value = stats.ttest_ind(members, non_members)

print("T-statistic:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Reject H0 → Rewards membership affects spending.")
else:
    print("Fail to reject H0 → No significant difference.")

T-statistic: 46.09549798256013
P-value: 0.0
Reject H0 → Rewards membership affects spending.



**• Since the p-value is less than 0.05, we reject the null hypothesis (H₀).**

**• This indicates that there is a statistically significant difference in spending between rewards members and non-members.**

**• Rewards members tend to spend more on average compared to non-members.**

**• This suggests that the loyalty program has a positive impact on customer spending behavior.**

In [24]:
df.head()

,customer_id,order_id,order_date,order_time,day_of_week,order_channel,store_id,store_location_type,region,customer_age_group,customer_gender,is_rewards_member,cart_size,num_customizations,total_spend,fulfillment_time_min,drink_category,has_food_item,order_ahead,customer_satisfaction
0,CUST_12974,ORD_00000001,2024-03-25,08:47:00,Mon,drive-thru,STR_340,Suburban,southwest,18-24,male,False,5,0,14.48,8.2,refresher,False,False,4
1,CUST_08235,ORD_00000002,2025-07-18,08:02:00,Fri,mobile app,STR_425,Urban,northeast,35-44,female,True,1,3,9.52,5.4,brewed coffee,False,True,4
2,CUST_00393,ORD_00000003,2025-01-15,05:40:00,Wed,kiosk,STR_103,Suburban,midwest,25-34,female,False,2,1,9.32,4.9,brewed coffee,False,False,5
3,CUST_06936,ORD_00000004,2024-07-30,15:10:00,Tue,drive-thru,STR_318,Suburban,midwest,25-34,female,True,2,1,9.55,3.5,refresher,False,False,4
4,CUST_09800,ORD_00000005,2024-06-18,07:38:00,Tue,drive-thru,STR_338,Suburban,northeast,35-44,female,False,3,1,12.24,4.1,frappuccino,False,False,3

## ANOVA Test

**The ANOVA (Analysis of Variance) test was conducted to determine whether there is a statistically significant difference in the average spending across different customer age groups.**

**H₀: There is no significant difference in the mean total spending across different customer age groups.**

**H₁: At least one customer age group has a significantly different mean spending compared to the others.**

In [25]:

groups = [group["total_spend"].values for name, group in df.groupby("customer_age_group")]

f_stat, p_value = stats.f_oneway(*groups)

print("F-statistic:", f_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Reject H0 → Spending differs across age groups.")
else:
    print("Fail to reject H0.")

F-statistic: 480.4351679530432
P-value: 0.0
Reject H0 → Spending differs across age groups.

**• Since the p-value is less than 0.05, we reject the null hypothesis (H₀).**

**• This indicates that average spending varies significantly across different customer age groups.**

**• The results suggest that age demographics play an important role in influencing customer spending behavior.**

**• Certain age groups contribute more to total revenue compared to others.**

## Chi-Square Test

**The Chi-Square test was conducted to determine whether there is a statistically significant relationship between region and order channel used by customers.**

**H₀: There is no significant relationship between region and order channel.**

**H₁: There is a significant relationship between region and order channel.**

In [26]:


contingency = pd.crosstab(df["region"], df["order_channel"])

chi2, p, dof, expected = stats.chi2_contingency(contingency)

print("Chi-square:", chi2)
print("P-value:", p)
if p < 0.05:
    print("Reject H0 → Region influences order channel.")
else:
    print("Fail to reject H0.")

Chi-square: 14.40530438862406
P-value: 0.2755783060737093
Fail to reject H0.

**• Since the p-value is greater than 0.05, we fail to reject the null hypothesis (H₀).**

**• This indicates that there is no statistically significant relationship between region and order channel.**

**• Customers across different regions tend to use similar ordering methods, such as mobile app, drive-thru, or in-store ordering.**

**• Regional location does not appear to strongly influence how customers place their orders.**

## Feature Engineering

Feature engineering involves creating new variables from existing data to enhance analytical insights and improve model performance.

New features can reveal hidden patterns in customer behavior and improve the overall quality of analysis.

In [27]:

df["order_hour"] = pd.to_datetime(df["order_time"], format="%H:%M:%S").dt.hour

df.head()

,customer_id,order_id,order_date,order_time,day_of_week,order_channel,store_id,store_location_type,region,customer_age_group,...,is_rewards_member,cart_size,num_customizations,total_spend,fulfillment_time_min,drink_category,has_food_item,order_ahead,customer_satisfaction,order_hour
0,CUST_12974,ORD_00000001,2024-03-25,08:47:00,Mon,drive-thru,STR_340,Suburban,southwest,18-24,...,False,5,0,14.48,8.2,refresher,False,False,4,8
1,CUST_08235,ORD_00000002,2025-07-18,08:02:00,Fri,mobile app,STR_425,Urban,northeast,35-44,...,True,1,3,9.52,5.4,brewed coffee,False,True,4,8
2,CUST_00393,ORD_00000003,2025-01-15,05:40:00,Wed,kiosk,STR_103,Suburban,midwest,25-34,...,False,2,1,9.32,4.9,brewed coffee,False,False,5,5
3,CUST_06936,ORD_00000004,2024-07-30,15:10:00,Tue,drive-thru,STR_318,Suburban,midwest,25-34,...,True,2,1,9.55,3.5,refresher,False,False,4,15
4,CUST_09800,ORD_00000005,2024-06-18,07:38:00,Tue,drive-thru,STR_338,Suburban,northeast,35-44,...,False,3,1,12.24,4.1,frappuccino,False,False,3,7

In [30]:
df["spend_category"] = pd.cut(
    df["total_spend"],
    bins=[0,10,20,30],
    labels=["Low","Medium","High"]
)

df["large_cart"] = df["cart_size"] > 5

df["morning_order"] = df["order_hour"] < 12

df["high_customization"] = df["num_customizations"] > 2

df["spend_per_item"] = df["total_spend"] / df["cart_size"]

df.head()

,customer_id,order_id,order_date,order_time,day_of_week,order_channel,store_id,store_location_type,region,customer_age_group,...,drink_category,has_food_item,order_ahead,customer_satisfaction,order_hour,spend_category,large_cart,morning_order,high_customization,spend_per_item
0,CUST_12974,ORD_00000001,2024-03-25,08:47:00,Mon,drive-thru,STR_340,Suburban,southwest,18-24,...,refresher,False,False,4,8,Medium,False,True,False,2.896
1,CUST_08235,ORD_00000002,2025-07-18,08:02:00,Fri,mobile app,STR_425,Urban,northeast,35-44,...,brewed coffee,False,True,4,8,Low,False,True,True,9.520
2,CUST_00393,ORD_00000003,2025-01-15,05:40:00,Wed,kiosk,STR_103,Suburban,midwest,25-34,...,brewed coffee,False,False,5,5,Low,False,True,False,4.660
3,CUST_06936,ORD_00000004,2024-07-30,15:10:00,Tue,drive-thru,STR_318,Suburban,midwest,25-34,...,refresher,False,False,4,15,Low,False,False,False,4.775
4,CUST_09800,ORD_00000005,2024-06-18,07:38:00,Tue,drive-thru,STR_338,Suburban,northeast,35-44,...,frappuccino,False,False,3,7,Medium,False,True,False,4.080

In [29]:
df[[
"spend_category",
"large_cart",
"morning_order",
"high_customization",
"spend_per_item"
]].head()

,spend_category,large_cart,morning_order,high_customization,spend_per_item
0,Medium,False,True,False,2.896
1,Low,False,True,True,9.520
2,Low,False,True,False,4.660
3,Low,False,False,False,4.775
4,Medium,False,True,False,4.080

In [31]:
df.to_csv(r"C:\Users\sainudheen\OneDrive - KEO International Consultants\Desktop\EDA_Project\Data\final_cleaned_day4.csv", index=False)

## Feature Engineering Insights

• The **spend_category** feature groups customers into Low, Medium, and High spenders, making it easier to analyze different spending levels.

• The **large_cart** feature identifies orders with more items, which usually leads to higher total spending.

• The **morning_order** feature helps detect whether orders are placed in the morning, showing peak ordering times.

• The **high_customization** feature identifies orders with many customizations, indicating customers who prefer personalized products.

• The **spend_per_item** feature shows the average amount spent per item in a cart, helping understand customer purchasing value.

• These engineered features help reveal customer behavior patterns and improve the quality of analysis.

# INSIGHTS

• Rewards program membership has a statistically significant impact on customer spending. Customers who are rewards members tend to spend more compared to non-members.

• Customer spending varies significantly across different age groups, indicating that age demographics influence purchasing behavior.

• Larger cart sizes are strongly associated with higher total spending, suggesting that customers purchasing more items contribute more to overall revenue.

• Most orders are placed during morning hours, indicating peak demand during typical coffee consumption periods.

• The mobile app ordering channel generates higher average spending compared to other order channels such as drive-thru, kiosk, and in-store cashier.

• Customer satisfaction ratings are generally high, with most customers giving ratings of 4 or 5, indicating a positive overall customer experience.

• Orders are distributed across different regions without a statistically significant association with the order channel, suggesting that channel preference is relatively consistent across regions.

• Customers who place highly customized orders represent a segment that values personalized products, which may contribute to higher engagement and satisfaction.

• The engineered feature spend_per_item provides insights into customer purchasing value and helps identify customers who spend more per product.

• Feature engineering helped uncover behavioral patterns such as large cart orders, morning purchasing behavior, and high customization orders, improving the overall analytical depth of the dataset.

# RECOMMENDATIONS

- **Strengthen loyalty programs** to encourage repeat purchases and increase customer engagement.

- **Focus marketing campaigns on high-spending age groups** to maximize revenue potential.

- **Promote mobile and digital ordering channels** to improve convenience and increase order frequency.

- **Use customer behavior data to design personalized promotions and offers**, which can improve customer retention and satisfaction.

- **Continuously monitor customer spending patterns and demographic trends** to support data-driven decision-making.